{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}{% trans 'Pterodactyl Module' %}{% endblock %}

{% set active_menu = 'extension' %}

{% set params = admin.extension_config_get({"ext":"mod_pterodactyl"}) %}

{% block content %}

<div class="widget first">
    <div class="head">
        <h5>{% trans 'Pterodactyl Module' %}</h5>
    </div>

    <div class="help">
        <h3>{% trans 'Pterodactyl Panel Module' %}</h3>
    </div>
    <div class="body">
        <a href="{{ 'extension/settings/pterodactyl'|alink }}">Module Settings</a> <br/>
    </div>
</div>
