{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}Pterodactyl Module Settings{% endblock %}
{% set active_menu = 'system' %}

{% block breadcrumbs %}
<ul>
    <li class="firstB"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li><a href="{{ 'system'|alink }}">{% trans 'Settings' %}</a></li>
    <li class="lastB">{% trans 'Pterodactyl Module Settings' %}</li>
</ul>
{% endblock %}

{% block content %}

<div class="widget">
    <div class="head">
        <h5 class="iCog">{% trans 'Pterodactyl Module Settings' %}</h5>
    </div>

  {% set params = admin.extension_config_get({"ext":"mod_pterodactyl"}) %}

  <form method="post" action="{{ 'api/admin/extension/config_save'|link }}" class="mainForm api-form" data-api-msg="{% trans 'Configuration updated' %}">

      <div class="help">
          <h3>{% trans 'Pterodactyl Module Settings' %}</h3>
          <p>{% trans 'There are a couple of things you need to specify before you can sell servers' %}</p>
      </div>

      <fieldset>
          <div class="rowElem noborder">
              <label>{% trans 'API Key' %}</label>
              <div class="formRight">
                  <input type="text" name="api_key" value="{{params.api_key}}" placeholder="{% trans 'API Key' %}"/>
              </div>
              <div class="fix"></div>
          </div>

          <div class="rowElem">
              <label>{% trans 'API Version' %}</label>
              <div class="formRight">
                  <input type="text" name="api_version" value="{{params.api_version}}" placeholder="{% trans 'v1' %}"/>
              </div>
              <div class="fix"></div>
          </div>

          <input type="submit" value="{% trans 'Update' %}" class="greyishBtn submitForm" />
          <input type="hidden" name="ext" value="mod_pterodactyl" />
      </fieldset>
  </form>
</div>

{% endblock %}
